# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import stt_pb2 as stt__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ListenerStub(object):
    """The Listener service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoSpeechToText = channel.stream_stream(
                '/SpeechToText.Listener/DoSpeechToText',
                request_serializer=stt__pb2.SpeechChunkRequest.SerializeToString,
                response_deserializer=stt__pb2.TranscriptStreamResponse.FromString,
                _registered_method=True)
        self.txt_to_speech = channel.stream_stream(
                '/SpeechToText.Listener/txt_to_speech',
                request_serializer=stt__pb2.TextRequest.SerializeToString,
                response_deserializer=stt__pb2.AudioResponse.FromString,
                _registered_method=True)


class ListenerServicer(object):
    """The Listener service definition.
    """

    def DoSpeechToText(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def txt_to_speech(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ListenerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoSpeechToText': grpc.stream_stream_rpc_method_handler(
                    servicer.DoSpeechToText,
                    request_deserializer=stt__pb2.SpeechChunkRequest.FromString,
                    response_serializer=stt__pb2.TranscriptStreamResponse.SerializeToString,
            ),
            'txt_to_speech': grpc.stream_stream_rpc_method_handler(
                    servicer.txt_to_speech,
                    request_deserializer=stt__pb2.TextRequest.FromString,
                    response_serializer=stt__pb2.AudioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SpeechToText.Listener', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SpeechToText.Listener', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Listener(object):
    """The Listener service definition.
    """

    @staticmethod
    def DoSpeechToText(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/SpeechToText.Listener/DoSpeechToText',
            stt__pb2.SpeechChunkRequest.SerializeToString,
            stt__pb2.TranscriptStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def txt_to_speech(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/SpeechToText.Listener/txt_to_speech',
            stt__pb2.TextRequest.SerializeToString,
            stt__pb2.AudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
