# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stt.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'stt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tstt.proto\x12\x0cSpeechToText\"+\n\x11RecognitionConfig\x12\x16\n\x0elanguage_codes\x18\x01 \x03(\t\"B\n\x0fStreamingConfig\x12/\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x1f.SpeechToText.RecognitionConfig\"T\n\x19StreamingRecognizeRequest\x12\x37\n\x10streaming_config\x18\x01 \x01(\x0b\x32\x1d.SpeechToText.StreamingConfig\"\x1d\n\x0c\x41udioRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"z\n\x12SpeechChunkRequest\x12+\n\x07\x63ontent\x18\x01 \x01(\x0b\x32\x1a.SpeechToText.AudioRequest\x12\x37\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\'.SpeechToText.StreamingRecognizeRequest\"5\n\x0b\x41lternative\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\"v\n\x16TranscriptStreamResult\x12\x19\n\x11result_end_offset\x18\x01 \x01(\x05\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12/\n\x0c\x61lternatives\x18\x03 \x03(\x0b\x32\x19.SpeechToText.Alternative\"n\n\x18TranscriptStreamResponse\x12\x1b\n\x13speech_event_offset\x18\x01 \x01(\x05\x12\x35\n\x07results\x18\x02 \x03(\x0b\x32$.SpeechToText.TranscriptStreamResult\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1e\n\rAudioResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x32\xbb\x01\n\x08Listener\x12`\n\x0e\x44oSpeechToText\x12 .SpeechToText.SpeechChunkRequest\x1a&.SpeechToText.TranscriptStreamResponse\"\x00(\x01\x30\x01\x12M\n\rtxt_to_speech\x12\x19.SpeechToText.TextRequest\x1a\x1b.SpeechToText.AudioResponse\"\x00(\x01\x30\x01\x42\x14\n\x12\x63om.google.asr.sttb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.google.asr.stt'
  _globals['_RECOGNITIONCONFIG']._serialized_start=27
  _globals['_RECOGNITIONCONFIG']._serialized_end=70
  _globals['_STREAMINGCONFIG']._serialized_start=72
  _globals['_STREAMINGCONFIG']._serialized_end=138
  _globals['_STREAMINGRECOGNIZEREQUEST']._serialized_start=140
  _globals['_STREAMINGRECOGNIZEREQUEST']._serialized_end=224
  _globals['_AUDIOREQUEST']._serialized_start=226
  _globals['_AUDIOREQUEST']._serialized_end=255
  _globals['_SPEECHCHUNKREQUEST']._serialized_start=257
  _globals['_SPEECHCHUNKREQUEST']._serialized_end=379
  _globals['_ALTERNATIVE']._serialized_start=381
  _globals['_ALTERNATIVE']._serialized_end=434
  _globals['_TRANSCRIPTSTREAMRESULT']._serialized_start=436
  _globals['_TRANSCRIPTSTREAMRESULT']._serialized_end=554
  _globals['_TRANSCRIPTSTREAMRESPONSE']._serialized_start=556
  _globals['_TRANSCRIPTSTREAMRESPONSE']._serialized_end=666
  _globals['_TEXTREQUEST']._serialized_start=668
  _globals['_TEXTREQUEST']._serialized_end=695
  _globals['_AUDIORESPONSE']._serialized_start=697
  _globals['_AUDIORESPONSE']._serialized_end=727
  _globals['_LISTENER']._serialized_start=730
  _globals['_LISTENER']._serialized_end=917
# @@protoc_insertion_point(module_scope)
